// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6CR4IReUFMQGMVH1TL3BUO9OhXgApi8',
    appId: '1:459779593905:web:bc71c45ee945954bc87490',
    messagingSenderId: '459779593905',
    projectId: 'authassignment-cf6a6',
    authDomain: 'authassignment-cf6a6.firebaseapp.com',
    storageBucket: 'authassignment-cf6a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOc5HgM31niHf9DgPr8O97X9SLdCr7oPQ',
    appId: '1:459779593905:android:78cb7be65e9b205cc87490',
    messagingSenderId: '459779593905',
    projectId: 'authassignment-cf6a6',
    storageBucket: 'authassignment-cf6a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjWDuBeHX1KykozIhkOh0izx-3smWgMo',
    appId: '1:459779593905:ios:c9bf0be7ecc1c06fc87490',
    messagingSenderId: '459779593905',
    projectId: 'authassignment-cf6a6',
    storageBucket: 'authassignment-cf6a6.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhjWDuBeHX1KykozIhkOh0izx-3smWgMo',
    appId: '1:459779593905:ios:c9bf0be7ecc1c06fc87490',
    messagingSenderId: '459779593905',
    projectId: 'authassignment-cf6a6',
    storageBucket: 'authassignment-cf6a6.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ6CR4IReUFMQGMVH1TL3BUO9OhXgApi8',
    appId: '1:459779593905:web:f1bcb5a963472c2bc87490',
    messagingSenderId: '459779593905',
    projectId: 'authassignment-cf6a6',
    authDomain: 'authassignment-cf6a6.firebaseapp.com',
    storageBucket: 'authassignment-cf6a6.appspot.com',
  );

}